version: '3'

services:
  app:
    build: .
    container_name: task-manager-app
    restart: always
    ports:
      - "1212:1212"
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONUNBUFFERED=1 